version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    main: ./cmd/ddenv/
    ldflags:
      - "-s -w "
      - "-X main.buildVersion={{.Version}}"
      - "-X main.buildCommit={{.Commit}}"
      - "-X main.buildDate={{.Date}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: "ddenv"
    description: "tool for maintaining a local environment for development"
    license: "Hippocratic License 3.0"
    homepage: "https://github.com/denisdefreyne/ddenv"
    dependencies:
      - name: shadowenv
    directory: "Formula"
    repository:
      owner: "denisdefreyne"
      name: "homebrew-tap"
    test:
      system "#{bin}/task", "--help"
    install: |-
      bin.install "ddenv"
